@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Nov 02 19:25:24 +0300 2024
REM SW Build 5164865 on Thu Sep  5 14:37:11 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim ForLoop_and_WhileLoop_3_behav -key {Behavioral:sim_1:Functional:ForLoop_and_WhileLoop_3} -tclbatch ForLoop_and_WhileLoop_3.tcl -view C:/Users/Mustafa/Desktop/Verilog/ForLoop_and_WhileLoop_3/ForLoop_and_WhileLoop_3_behav.wcfg -log simulate.log"
call xsim  ForLoop_and_WhileLoop_3_behav -key {Behavioral:sim_1:Functional:ForLoop_and_WhileLoop_3} -tclbatch ForLoop_and_WhileLoop_3.tcl -view C:/Users/Mustafa/Desktop/Verilog/ForLoop_and_WhileLoop_3/ForLoop_and_WhileLoop_3_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
